variable "asgName" {}
variable "lcName" {}
variable "subnets" {}
variable "asgMin" {}
variable "asgMax" {}
variable "asgDesiredcapacity" {}
variable "asgHelthCheckGracePeriod" {}
variable "asgHelathCheckType" {}
variable "tgArn" {}