variable "tgName" {}
variable "vpc" {}
variable "albHelathCheck" {}
variable "albInterval" {}
variable "healthyCount" {}
variable "albPath" {}
variable "albPort" {}
variable "albProtocol" {}
variable "timeoutPeriod" {}
variable "unhealthyCount" {}
variable "albResultCode" {}
